spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: GSMHRM
    url: jdbc:mysql://localhost:3306/gsmhrm
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update

  main:
      allow-bean-definition-overriding: 'true'

server:
  port: 9020

