spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true

  datasource:
    driver-class-name: ${DB_CLASS}
    username: ${DB_USER}
    url: ${DB_URL}
    password: ${DB_PASSWORD}

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USER}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth:
          starttls:
            enable: true
    default-encoding: UTF-8

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  main:
    allow-bean-definition-overriding: 'true'
  data:
    redis:
      host: ${R_HOST}
      port: ${R_PORT}

jwt:
  accessSecret: ${ACCESS_SECRET}
  refreshSecret: ${REFRESH_SECRET}

server:
  port: '9040'

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
