spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: GSMHRM
    url: jdbc:mysql://localhost:3306/gsmhrm
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
server:
  port: '9010'