spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: GSMHRM
    url: jdbc:mysql://localhost:3306/gsmhrm
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
  main:
    allow-bean-definition-overriding: 'true'
server:
  port: '9010'

jwt:
  accessSecret: youcantrevealthesecretkey1234012300040
  refreshSecret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  secret: happilyeverafterhappilyeverafter